name: ionhive
description: "Ion Hive - Your ultimate companion for finding, charging, and managing EV stations effortlessly."
publish_to: "none"

version: 1.0.3+4

environment:
  sdk: ">=3.6.0 <3.8.0"  # Already updated to support Dart 3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  pinput: ^5.0.0
  flutter_spinkit: ^5.2.1
  package_info_plus: ^8.3.0
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.3.4
  connectivity_plus: ^5.0.2
  permission_handler: ^11.3.1
  webview_flutter: ^4.10.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  flutter_blue_classic: ^0.0.3  # Still outdated; consider alternatives
  webview_flutter_wkwebview: ^3.17.0
  intl_phone_field: ^3.2.0
  google_fonts: ^6.2.1
  flutter_swiper_null_safety: ^1.0.2  # Still outdated; consider replacing with carousel_slider
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  fui_kit: ^2.0.2  # Check for updates or alternatives
  cached_network_image: ^3.4.1
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  path_provider: ^2.1.5
  razorpay_flutter: ^1.4.0  # Downgraded as per compatibility requirements
  fluttertoast: ^8.2.12
  open_file: ^3.5.10
  share_plus: ^10.0.0
  mobile_scanner: ^5.2.1
  qr_flutter: ^4.1.0
  web_socket_channel: ^3.0.1
  flutter_local_notifications: ^19.2.0
  # Replaced slider_button and vibration with more modern alternatives
  slide_to_act: ^2.0.2
  flutter_haptic_feedback: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 600

  assets:
    - assets/ionHive_logo/ionHive.png
    - assets/Image/
    - assets/icons/
    - assets/Map/Map.json
    - assets/Map/DarkMap.json

flutter_native_splash:
  color: "#000000"
  image: assets/ionHive_logo/ionHive.png  # Fixed path by removing incorrect single quote
  android: true
  ios: true
  web: true
  fullscreen: true